# Generated by Django 3.2.7 on 2023-01-11 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('karseva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(blank=True, max_length=20)),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(blank=True, max_length=30)),
                ('isActive', models.BooleanField()),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 11, 11, 9, 58, 623119, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(blank=True, choices=[('USER', 'USER'), ('VOLUNTEER', 'VOLUNTEER'), ('ADMIN', 'ADMIN')], max_length=15),
        ),
    ]
