# Generated by Django 3.2.7 on 2023-01-11 12:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('karseva', '0003_auto_20230111_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='modifiedBy',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='modifiedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='modifiedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 11, 12, 35, 43, 459857, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requeststatus',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 11, 12, 35, 43, 459857, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
