# Generated by Django 3.2.7 on 2023-01-13 17:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('karseva', '0019_auto_20230113_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userratings',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userratings',
            name='serviceRequest',
        ),
        migrations.AddField(
            model_name='userratings',
            name='ratingCount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userratings',
            name='ratingNumber',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 13, 17, 31, 13, 788687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='modifiedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 13, 17, 31, 13, 788687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='lastModifiedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 13, 17, 31, 13, 788687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requestCreatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 13, 17, 31, 13, 788687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requestTimeInBound',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 13, 17, 31, 13, 788687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requestTimeOutBound',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 13, 17, 31, 13, 788687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 13, 17, 31, 13, 788687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='modifiedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 13, 17, 31, 13, 788687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userratings',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
