# Generated by Django 3.2.7 on 2023-01-14 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import karseva.models


class Migration(migrations.Migration):

    dependencies = [
        ('karseva', '0021_auto_20230115_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 14, 18, 48, 31, 733861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='modifiedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 14, 18, 48, 31, 733861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='lastModifiedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 14, 18, 48, 31, 733861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requestCreatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 14, 18, 48, 31, 733861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requestTimeInBound',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 14, 18, 48, 31, 733861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requestTimeOutBound',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 14, 18, 48, 31, 733861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='unique_no',
            field=models.CharField(blank=True, default=karseva.models.ServiceRequest.create_new_unique_no, max_length=8),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 14, 18, 48, 31, 733861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='modifiedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 14, 18, 48, 31, 733861, tzinfo=utc)),
        ),
    ]
