# Generated by Django 3.2.7 on 2023-01-29 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('karseva', '0037_auto_20230128_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 29, 8, 58, 36, 619144, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='modifiedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 29, 8, 58, 36, 619144, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='lastModifiedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 29, 8, 58, 36, 619144, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requestCreatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 29, 8, 58, 36, 619144, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 29, 8, 58, 36, 619144, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='modifiedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 29, 8, 58, 36, 619144, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(blank=True, choices=[('VOLUNTEER CHANGE', 'VOLUNTEER CHANGE'), ('STATUS CHANGE', 'STATUS CHANGE'), ('DESCRIPTION CHANGE', 'DESCRIPTION CHANGE'), ('TIME CHANGE', 'TIME CHANGE'), ('FEEDBACK', 'FEEDBACK'), ('RATING', 'RATING'), ('OTHER', 'RATING')], max_length=30, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karseva.servicerequest')),
            ],
        ),
    ]
